FROM jenkins/jenkins:lts

LABEL maintainer="steve@bargelt.com"

RUN /usr/local/bin/install-plugins.sh jdk-tool jclouds-jenkins token-macro durable-task yet-another-docker-plugin docker-workflow docker-plugin
